# fly.toml app configuration file generated for young-rain-9767 on 2023-05-21T06:14:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-rain-9767"
primary_region = "nrt"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_URL = "https://young-rain-9767.fly.dev"
  APP_NAME = "microposts"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.jwrennbkiaxuhccwazoy.supabase.co"
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
